<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="pt_BR">
<context>
    <name>CTCron</name>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="110"/>
        <source>No password entry found for uid &apos;%1&apos;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="249"/>
        <source>File generated by Crontablib the %1.</source>
        <comment>Generation Message + current date</comment>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="289"/>
        <source>&lt;em&gt;No output.&lt;/em&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="295"/>
        <source>&lt;em&gt;No error.&lt;/em&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="301"/>
        <source>&lt;p&gt;&lt;strong&gt;Command:&lt;/strong&gt; %1&lt;/p&gt;&lt;strong&gt;Command could not be started&lt;/strong&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="305"/>
        <source>&lt;p&gt;&lt;strong&gt;Command:&lt;/strong&gt; %1&lt;/p&gt;&lt;strong&gt;Standard Output :&lt;/strong&gt;&lt;pre&gt;%2&lt;/pre&gt;&lt;strong&gt;Error Output :&lt;/strong&gt;&lt;pre&gt;%3&lt;/pre&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="312"/>
        <source>An error occurred while updating crontab.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="321"/>
        <source>Unable to open crontab file for writing</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="322"/>
        <source>The file %1 could not be opened.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>CTDayOfMonth</name>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="22"/>
        <source>every day </source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>1st</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>2nd</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>3rd</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>4th</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>5th</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>6th</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>7th</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>8th</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>9th</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>10th</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>11th</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>12th</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>13th</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>14th</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>15th</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>16th</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>17th</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>18th</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>19th</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>20th</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>21st</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>22nd</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>23rd</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>24th</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>25th</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>26th</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>27th</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>28th</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>29th</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>30th</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>31st</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>CTDayOfWeek</name>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="43"/>
        <source>every day </source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Mon</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Tue</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Wed</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Thu</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Fri</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Sat</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Sun</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Monday</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Tuesday</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Wednesday</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Thursday</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Friday</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Saturday</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Sunday</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>CTGlobalCron</name>
    <message>
        <location filename="../crontablib/ctGlobalCron.cpp" line="28"/>
        <source>All users</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>CTHost</name>
    <message>
        <location filename="../crontablib/cthost.cpp" line="59"/>
        <source>You have been blocked from using Crontablib                          by either the /etc/cron.allow file or the /etc/cron.deny file.                          

Check the crontab man page for further details.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/cthost.cpp" line="141"/>
        <source>User %1: %2</source>
        <comment>User login: errorMessage</comment>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>CTMonth</name>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="22"/>
        <source>every month</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>January</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>February</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>March</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>April</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>May</source>
        <comment>May long</comment>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>June</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>July</source>
        <comment>July long</comment>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>August</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>September</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>October</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>November</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>December</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>CTSystemCron</name>
    <message>
        <location filename="../crontablib/ctSystemCron.cpp" line="46"/>
        <source>System Crontab</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>CTTask</name>
    <message>
        <location filename="../crontablib/cttask.cpp" line="233"/>
        <source>at system startup</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="240"/>
        <source>%1, %2</source>
        <comment>1:Time Description, 2:Date Description</comment>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="245"/>
        <source>every %1</source>
        <comment>Every &apos;days of week&apos;</comment>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="249"/>
        <source>%1 of %2</source>
        <comment>&apos;Days of month&apos; of &apos;Months&apos;</comment>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="262"/>
        <source>every day </source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="273"/>
        <source>%1 as well as %2</source>
        <comment>1:Day of month, 2:Day of week</comment>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="305"/>
        <source>%1:%2</source>
        <comment>1:Hour, 2:Minute</comment>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="315"/>
        <source>, and </source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="317"/>
        <source> and </source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="320"/>
        <source>, </source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="326"/>
        <source>at %1</source>
        <comment>Hour::Minute list</comment>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="333"/>
        <source>Every minute</source>
        <comment>Every minute</comment>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>CTUnit</name>
    <message>
        <location filename="../crontablib/ctunit.cpp" line="170"/>
        <source>,</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctunit.cpp" line="171"/>
        <source> and </source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctunit.cpp" line="174"/>
        <source>, </source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>CTVariable</name>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="123"/>
        <source>Override default home folder.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="126"/>
        <source>Email output to specified account.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="129"/>
        <source>Override default shell.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="132"/>
        <source>Folders to search for program files.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="135"/>
        <source>Dynamic libraries location.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="138"/>
        <source>Local Variable</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
